

name: main3

# on:
#   schedule:
#     - cron: "*/5 * * * *"
on:
  create
  # pull_request_target:
  #   types: [opened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: 'x64'
    - name: Create local changes
      run: |
        wget --no-check-certificate https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/main/src/config.json -O-|jq '.blacklist[]' -c -r |sort|uniq|sed 's/^/\|\|/g;s/$/^/g' > .metamask_anti_fish.txt
        cat .append .metamask_anti_fish.txt > metamask_anti_fish.txt
    - name: Commit files
      run: |
        git config --local user.email "workflow@git.local"
        git config --local user.name "workflow(bot)"
        git commit -m "Update today's list on $(date +%Y-%m-%d)" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
