

name: update for measkmask anti fish rule

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-python@v1
      #with:
      #  python-version: 3.7
      #  architecture: 'x64'
    - name: Create local changes
      run: |
        wget --no-check-certificate https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/main/src/config.json -O-|jq '.blacklist[]' -c -r |sort|uniq|sed 's/^/\|\|/g;s/$/^/g' > .metamask_anti_fish.txt
        cat .append .metamask_anti_fish.txt > metamask_anti_fish.txt
    - run: if [[ "$(git diff --exit-code metamask_anti_fish.txt)" =~ 'diff' ]]; then echo "IS_VALID=true" >> $GITHUB_ENV; else echo "IS_VALID=false" >> $GITHUB_ENV ;fi
    - if: ${{ env.IS_VALID == 'true' }}
      name: Commit files
      run: |
        git config --local user.email "workflow@git.local"
        git config --local user.name "workflow(bot)"
        git add -A
        git commit -m "Update today's list on $(date +%Y-%m-%d)" -a
    - if: ${{ env.IS_VALID == 'true' }}
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
